# Generated by Django 4.2.5 on 2023-09-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FIRSTAPPLICATION", "0002_alter_customerdetails_contact_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("contact_number", models.CharField(max_length=10)),
                ("City", models.CharField(max_length=30)),
            ],
        ),
    ]
