# Generated by Django 4.2.5 on 2023-09-12 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FIRSTAPPLICATION", "0003_employeedetails"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EmployeeDetails",
            new_name="EmployeeDetail",
        ),
    ]
