# Generated by Django 4.2.5 on 2023-09-12 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FIRSTAPPLICATION", "0004_rename_employeedetails_employeedetail"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CustomerDetails",
            new_name="CustomerDetail",
        ),
    ]
