# Generated by Django 4.2.5 on 2023-09-13 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FIRSTAPPLICATION", "0005_rename_customerdetails_customerdetail"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmployeeDetail",
        ),
    ]
